### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by stugol** [ozra/onyx-lang#2]
This looks interesting, but doesn't seem to get many updates. Is the project still alive?

The option of an alternative syntax for Crystal appeals to me - uppercase/lowercase restrictions for instance are particularly irritating. I hope the project isn't dead.

**Comment by stugol** [comment]
Dashed identifiers appeal to me as well.

**Comment by ozra** [comment]
Ah, no, I've just coded very ad hoc, so I wanted to wait push until there was something more usable. There is now.

Well, I think there might be many things you like, I'll post issues for RFC that doubles as comments during tomorrow.

But... constants _are_ uppercase, and variables _are_ lowercase, that's one of the (few) things that are the same - so that might put you off. It actually does make code clearer imo.

I do raise that particular question in its particular RFC though, so please chime in tomorrow when I've posted that. Nothing's cut in stone yet - that's the point.

**Comment by stugol** [comment]
Where are you raising this question?

**Comment by ozra** [comment]
#9
