### ISSUE TITLE
Concurrency

### ISSUE THREAD

**Issue by stugol** [ozra/onyx-lang#25]
Crystal's concurrency is truly awful. Onyx should support true threading.

Please? ;)

**Comment by ozra** [comment]
_Simple answer_: without doubt!

_Practical answer_ that you might not like so much (me neither):

As an Onyxeer, one must consider one self a part of the crystal family. Onyx relies and inter operates deeply with crystal AST, and relies on the stdlib. It couldn't possibly exist in the current state without it (add x years of development).

As, you know from issues on crystal, we are _a lot_ of people who want solid concurrency. There's just no magic way of short cutting there - unless you have a couple of million quid to pour into the project(s)?

The crystal team has done an impressive job.

In the discussion regarding reworking the compilation passes, it becomes apparent that they prioritize time on those changes first, which I agree is important. You can't build a house without the foundation in place.

And as for me, I'm in "lang implementation mode" too. And since onyx has both onyx _and_ crystal nodes flying around, conditionally compiling them differently, until merging in a canonical form that compile to a program together, I will have to do _a lot of refactoring_ after those (welcome) changes are in place, to maintain compatibility.

Thougths:
- Threading is naturally a must in Onyx (and access to lower levels of it for when _really needed_ also [as always KISS first, go in to the abyss only if really necessary])
- My time is limited as everyone's, and I would even need more solely for Onyx lang alone. Working on an alt. stdlib too would be impossible currently.
- Therefore a longer perspective on this and trying to work out a good model with/in crystal community that will benefit us all would be the option that actually gets us a solid model of concurrency the fastest.

**In essence: best way forward for this issue currently**:
- Discuss it further in _crystal_ issues so that a suitable solution becomes the goal.
- Help out in implementing agreed ideas, if you have the capability and time.

**Comment by stugol** [comment]
I'm quite prepared to help out, but I don't understand how compilers work.

**Comment by ozra** [comment]
Just ask at any time, and you'll get some pointers..

**Comment by stugol** [comment]
Ah, but will I be able to _dereference_ them? ;)

**Comment by ozra** [comment]
They, may be unsafe! ;-)

**Comment by stugol** [comment]
Asterite doesn't seem to consider threading a high priority. I, on the other hand, maintain that it's the single most important thing he should be be working on at this time.

If you're not willing to implement proper threading at the moment, could you at least patch `IO` so calls like `puts` don't crash horribly when called from another thread?

While there are many areas in which I can be of use - writing documentation, for example - compiler design is not one of them; so I can't be of any direct assistance in this case.

**Comment by ozra** [comment]
In any event it'll have to wait until macros and the basic foundation of Onyx is in place. I can't work on two things at the same time either you know, and with an incomplete foundation, installing fancy door-ways with bells and whistles can't happen ;-)

**Comment by ozra** [comment]
Tracked in #79 from now on...
