### ISSUE TITLE
Feature request: Heterogeneous arrays

### ISSUE THREAD

**Issue by stugol** [ozra/onyx-lang#29]
In Crystal, tuples are heterogenous, but cannot be extended or modified at runtime; while Arrays are extensible but homogenous. Ideally:
```
my-array = ["", 2, nil]
my-array << false
puts my-array.class				-- should NOT be String | Int | Nil | Bool,
								-- but rather [String, Int, Nil, Bool], like a tuple
```
Come to think of it, might be better to turn this on its head: keep arrays homogenous, but make tuples editable:
```
my-tuple = {"", 2, nil}
my-tuple << false
puts my-tuple.class				-- {String, Int, Nil, Bool}
```

**Comment by ozra** [comment]
This is pretty much an impossible feat. It mixes the domains of static type resolution and run time value resolution.
For type to be certain - in a certain position - the container cannot be dynamically extended, because then there cannot be a guarantee that the position actually holds a value of the promised type. And hence, strong type checking crumbles into a pile of doo doo.

Why would you possibly need it?

**Comment by stugol** [comment]
Relaxed typing [here](https://github.com/ozra/onyx-lang/issues/27#issuecomment-188511633) would probably solve this.

Also an example.

**Comment by ozra** [comment]
Does that issue suffice, we're on to something there, maybe this can be closed?

**Comment by stugol** [comment]
Sure, it should be a decent alternative. And more useful.
