### ISSUE TITLE
Feature request: Different syntax for array and hash types

### ISSUE THREAD

**Issue by stugol** [ozra/onyx-lang#31]
[Swift](https://developer.apple.com/swift/) and Objective C allow for the following syntactic sugar for array types. I suggest also a variant for hashes:

- `Array(T)` can be written `[T]`
- `Hash(K,V)` can be written `{K => V}`

Example:
```
a-function(messages [String], pairs {String => String}) ->

messages [String] = ["hi"]
pairs {String => String}
a-function messages, pairs
```

**Comment by stugol** [comment]
Bump

**Comment by ozra** [comment]
I didn't implement type sugar for List for two (one) reason(s):
- `[` / `]` are used in generics, it would make it _a bit_ fuzzier discerning (being used in the same context).
- I'm still holding it open as whether free type vars should be allowed to have type-like names, instead of the "[A-Z]\d?" duck-lex pattern now in use. The idea was that introducing a generic then would be done by surrounding it with the generic-delimiters, which would be a 100% syntactic clash.

That said, I think "duck-lexing" holds for very concise, no nonsense focus-on-the-guts programming, so I personally don't see a need for extending the "namability" of generic args/free type vars. But even then, another notation could be used.

So it's open for discussion.

As for the Map syntax, the reason was simple: it's only _one_ char difference (spaced notation) between formal and sugar-notation, and the formal one then makes code more consistent _and_ holistically a bit more clear.

```onyx
a-function(pairs {Str => Str}) ->

b-function(pairs Map[Str,Str]) ->

c-function(pairs Map[Str, Str]) ->
```

But I'm open to thinking a bit more about both of these.

**Comment by stugol** [comment]
Then limit generics to using `< >` and have `[ ]` for an array type. I see the point of having more than one symbol for generics, but put it this way: If you have more than a couple of nested generics in an expression, your code will be hard to read anyway. This isn't C++, use a type alias or something. Besides, is it really worth throwing away _both_ types of delimiter on the same meaning?

Plus, limiting free type vars to a single character would still clash with `[ ]`, so the length of a type var is not relevant.

Also, I propose that you disallow spaces before free var declarations:
```
type thing<T>		- fine
type thing <T>		-- error
```
If you're mandating spaces around operators anyway, this makes a lot of sense.

Even if you go with `Map`, I'd like to have the _option_ of using `{ K => V }` if I want to. To me, it looks better. Incidentally, would `=>` need spaces around it?

Is there a difference between an `Array` and a `List`?

**Comment by ozra** [comment]
> This isn't C++, use a type alias or something.

Hahaha, it's so funny, in my initial write up about generics, I pretty much wrote that exact line :-)
We think alike on some things, and very unlike on some things. That's a great recipe for progress!

> Besides, is it really worth throwing away both types of delimiter on the same meaning?

This too is an issue I raised in regards to these, it's good that you raised it too, reminding me of the importance.

I'm definitely open to ditching `[ ]` for generics

Regarding the type var, the clash would arise because in `a(x [Tee], y Tee) Tee ->` - the `[Tee]` would signify introduction of a type var. With `T*` that is not necessary (it's not really anyway, but increase the risk of misspelling types and it compiling anyway because it resolves to a type var!), but in any event, if keeping only `< >` even that would not be a problem, and that also is just one loose suggestion on how such a syntax would be formed.

Spaces are already forbidden before generic params/args - to ensure no problems arise with their use as operators, so it's halfway there.

I agree that the sugar looks... more "mathematical", and clearer in representing the value's construction.
`=>` would not require to be spaced (unless strict general rules for spacing should be introduced, but personally I don't see a need to force it unless really high risk of confusion in constructs).

List in Onyx is _exactly_ what Array is in Crystal, Map is exactly Hash, I simply think they're more fitting names, and the standard types in the language are important to name appropriately too imo.

**Comment by stugol** [comment]
Sounds good.

**Comment by ozra** [comment]
I've had some minutes to examine this a little today.

Neither of the proposed syntaxes works since they follow the exact same form of their corresponding value producing literal.

Example:

```
a(x) -> say "a says: '{x}' and '{x[String]}'"
a {String => String}   --> "a says 'String => String' and 'String'"

b(x) -> say "b says: '{x}' and '{x.first}'"
b [String]   --> "b says: '[String]' and 'String'"
```

**Comment by stugol** [comment]
By that reasoning, the entire variable declaration syntax is broken:
```
a(x) -> say "It's an {x}"
a Int      -> "It's an Int"
```

**Comment by ozra** [comment]
No - there's a difference.

Typing vars in expression blocks (ie in functions and program scope) is not yet in place. But when it is, a type signifier must be used in that context (it would be seldom it would be used in code):
```onyx
a(x) -> say "It's an {x}"
a Int      -> "It's an Int"
b 'Int = 47
```

_The_ difference is that
```
a Int         -- gets an Int-type as value
a {Str => Str}   -- gets a Map-type _instance_ of type Map<Str.class, Str.class>
```

I will continue to work on it, thinking about it, because I really agree list-sugar should be in, so might as well figure out both!

**Comment by ozra** [comment]
(sidenote: there's a hyphen missing in the comment after `a Int`, should be `-->` to be a comment.)

**Comment by stugol** [comment]
Then I don't see the problem:
```
a [Int]      -- pass an array to function a
a '[Int]     -- declare `a` of type Array(Int)

fn(a [Int]) ->       -- declare a function taking an array of Int
```
If variable typing must include a `'` anytime a function call may be intended, then the problem solves itself.

**Comment by ozra** [comment]
That the syntax (relating to the very same thing) changes meaning based on context is confusing. When restricting a variable the syntax means one thing, when used in expression something completely different.

Ideas off the top of the head, that unfortunately doesn't look as good though:
```
a(x Int[]) ->
-- alt.
a(x []Int) ->

a(y Str=>Str) ->
-- alt.
a(y Str:Str) ->
```

**Comment by stugol** [comment]
No, I think the duality is fine:
```
type X ->
x = X()
something = [x]        -- an array containing x
fn(v [X]) ->           -- an array containing values of type X
```
Sounds perfectly reasonable to me.

**Comment by ozra** [comment]
Revisiting. An "officialy OK'ed" alias for `List` in Onyx will be (is) `Li` (references to web-world should work for all programmers ;-) ). With this, it's very terse to form type declarations with the canonical syntax:

``` onyx
type Foo

my-fn(v Li‹Foo›) -> v
```

I prefer the path chosen of very terse "standard types" names, making standard syntax clearer than sugar  for type-decls in many cases.

Unrelated example:

``` onyx
my-fn(f Fn‹Intd, Bool›) -> f(1)
```

instead of:

``` onyx
my-fn(f (Intd) -> Bool) -> f(1)
```

The sugar here is _less_ clear then the canonical form.
